import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Mackie lab</h1>
      </main>
    </>
  );
};

console.log(process.env.MACKIE_LAB_API_KEY);

export default Home;