import Link from "next/link";
import type { InferGetStaticPropsType, NextPage } from "next";
import { client } from "../libs/client"; // srcから見た絶対パスで指定
import type { Blog, Tags } from "../types/blog"; // srcから見た絶対パスで指定
import { Header } from "../components/Header";
import  Head  from "next/head";

// microCMSへAPIリクエスト
export const getStaticProps = async () => {
  const blog = await client.get({ endpoint: "blog" });
  const tags = await client.get({ endpoint: "tags" });

  return {
    props: {
      blogs: blog.contents,
      tags: tags.contents,
    },
  };
};

// Props（blogsとtags）の型
type Props = {
  blogs: Blog[];
  tags: Tags[];
};

const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({ blogs, tags }: Props) => {
  console.log(blogs);
  console.log(tags);
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ul>
        {blogs.map(blog => (
          <li key={blog.id}>
            <Link href={`/blog/${blog.id}`}>
              <a>{blog.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
